// Generated by Haxe 4.2.1+bf9ff69
(function ($global) { "use strict";
function Main_main() {
	console.log("src/Main.hx:2:","Testing PokeAPI");
	var pokedex = new Pokedex();
	pokedex.getPokemonByName("pikachu").then(function(value) {
		console.log("src/Main.hx:6:",value.name);
	});
	pokedex.getAbilityByName("stench").then(function(value) {
		console.log("src/Main.hx:9:",value.names);
	});
}
var Pokedex = require("pokedex-promise-v2");
var haxe_iterators_ArrayIterator = function(array) {
	this.current = 0;
	this.array = array;
};
haxe_iterators_ArrayIterator.prototype = {
	hasNext: function() {
		return this.current < this.array.length;
	}
	,next: function() {
		return this.array[this.current++];
	}
};
Main_main();
})({});
